version: '3.8'

services:
  ar-wayfinder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ar-wayfinder
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=your-domain.com
      - ADMIN_EMAIL=admin@your-domain.com
    restart: unless-stopped
    volumes:
      - letsencrypt-data:/etc/letsencrypt

volumes:
  letsencrypt-data:
