name: ar-campus-wayfinder

services:
  - type: web
    name: ar-wayfinder
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    repo: https://github.com/TheArtOfPour/ar-campus-wayfinder
    branch: main
    buildCommand: npm run build
    startCommand: npx serve -s dist -l $PORT
    environment:
      NODE_ENV: production
    regions:
      - aws:us-east-1
